version: '2'
services:
    gutenberg-app:
        image: gutenberg
        external_links:
            - gutenberg-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=Gutenberg
        ports:
            - 8080:8080
    gutenberg-mongodb:
        extends:
            file: mongodb.yml
            service: gutenberg-mongodb
