version: '2'
services:
    gutenberg-mongodb:
        container_name: gutenberg-mongodb
        image: mongo:3.2.3
        ports:
            - "27017:27017"
        command: mongos --configdb gutenberg-mongodb-config
    gutenberg-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    gutenberg-mongodb-config:
        image: mongo:3.2.3
        container_name: gutenberg-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
