version: '2'
services:
    gutenberg-mongodb:
        container_name: gutenberg-mongodb
        image: mongo:3.2.3
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/Gutenberg/mongodb/:/data/db/
